name: proje
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scikit-learn
  - pillow
  - pip
  - pip:
      - tensorflow==2.15.0
      - keras==2.15.0
